export const MINIMUM_SCORE = 0.9;
export const MAX_NEAR_ARMS_DISTANCE = 1;
export const MIN_OPEN_ARMS_DISTANCE = 2;

export const OPEN_ARMS_MAX_DISTANCE_FROM_SHOULDER = 0.5;

export const SIDEWAYS_BODY_MAXIMUM_RATIO = 0.3;
