export const LEFT_KNEE_ANGLE_MIN_LIMIT = 170
export const LEFT_KNEE_ANGLE_MAX_LIMIT = 195

export const RIGHT_KNEE_ANGLE_MIN_LIMIT = 140
export const RIGHT_KNEE_ANGLE_MAX_LIMIT = 195

export const LEFT_SHOULDER_ANGLE_MIN_LIMIT = 10
export const LEFT_SHOULDER_ANGLE_MAX_LIMIT = 35

export const RIGHT_ELBOW_ANGLE_MIN_LIMIT = 158
export const RIGHT_ELBOW_ANGLE_MAX_LIMIT = 195

export const LEFT_ELBOW_ANGLE_MIN_LIMIT = 170
export const LEFT_ELBOW_ANGLE_MAX_LIMIT = 195

export const DISTANCE_ARMS_MIN_LIMIT = 120
export const DISTANCE_ARMS_MAX_LIMIT = 250

export const DISTANCE_SHOULDERS_MIN_LIMIT = 0
export const DISTANCE_SHOULDERS_MAX_LIMIT = 80

export const DISTANCE_HIPS_MIN_LIMIT = 0
export const DISTANCE_HIPS_MAX_LIMIT = 80

export const DISTANCE_KNEES_MIN_LIMIT = 0
export const DISTANCE_KNEES_MAX_LIMIT = 80

export const DISTANCE_ANKLES_MIN_LIMIT = 0
export const DISTANCE_ANKLES_MAX_LIMIT = 80

export const DISTANCE_FROM_WRIST_AND_HIP_MIN_LIMIT = 0
export const DISTANCE_FROM_WRIST_AND_HIP_MAX_LIMIT = 80
