export const LEFT_KNEE_ANGLE_MIN_LIMIT = 170
export const LEFT_KNEE_ANGLE_MAX_LIMIT = 195

export const RIGHT_KNEE_ANGLE_MIN_LIMIT = 140
export const RIGHT_KNEE_ANGLE_MAX_LIMIT = 195

export const LEFT_SHOULDER_ANGLE_MIN_LIMIT = 10
export const LEFT_SHOULDER_ANGLE_MAX_LIMIT = 35

export const RIGHT_ELBOW_ANGLE_MIN_LIMIT = 158
export const RIGHT_ELBOW_ANGLE_MAX_LIMIT = 195

export const LEFT_ELBOW_ANGLE_MIN_LIMIT = 170
export const LEFT_ELBOW_ANGLE_MAX_LIMIT = 195

export const DISTANCE_ARMS_MIN_LIMIT = 150
export const DISTANCE_ARMS_MAX_LIMIT = 260
